# -*- coding: utf-8 -*-
"""Ev2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bi1_StLtKQCGrHXFsVyaU_CYCx-6g_jm
"""

import datetime
import random


sala = {}
clientes = {}
lista_reservaciones = []
listas_datos_finales = []
reservaciones = {}
procede = 0

print("*" * 100)

while True:
    print("MENU DE RESERVACION DE SALAS")
    print("1-Registrar la reservación de una sala")
    print("2-Editar el nombre del evento de una reservación ya hecha")
    print("3-Consultar las reservaciones existentes para una fecha específica")
    print("4-Registrar a un nuevo cliente")
    print("5-Registrar una sala")
    print("6-Salir")
    opciones = input("¿Cual opcion quiere escoger?: \n")

    try:
        opciones_1 = int(opciones)
    except ValueError:
        print("Opcion Incorrecta")
    except Exception:
        print("Se ha presentado una excepcion:")
        print(Exception)

    if opciones_1 == 1:
      cliente = input("¿Es usted un cliente registrado?\n")
      if cliente == 'Si':
         salas = input("Ingrese la sala a reservar\n")
         regis_cliente = input("Ingrese su nombre de cliente\n")
         evento = input("Ingrese el evento a reservar\n")
         folio = print(f"Su folio es {random.randrange(2000000)}\n")
         print("Turnos: \n Matutino\n Vespertino\n Nocturno\n")
         turno = input("Ingrese el turno a reservar en mayusculas\n")
         fecha_actual = datetime.date.today()
         while procede == 0:
             fecha_capturada = input("Ingresa la fecha a reservar con este formato dd/mm/aaaa: \n")
             fecha_procesada = datetime.datetime.strptime(fecha_capturada, "%d/%m/%Y" ).date()
             print(f"la fecha que estas solicitando es: {fecha_procesada}\n")
             cant_dias = 2
             nueva_fecha = fecha_procesada + datetime.timedelta(days=-cant_dias)
             if fecha_actual < nueva_fecha:
                 print("su registro se completara con exito\n")
                 print(f"Su fecha se confirma registrada para, {fecha_procesada}\n")
                 procede = procede + 1
                 lista_reservaciones = [fecha_procesada, salas, regis_cliente, evento, turno]
                 listas_datos_finales = [lista_reservaciones]
             else:
                print("La fecha no cumple con el requisito de 2 dias de anticipacion")
                print("Porfavor intente con otra fecha\n") 

      elif cliente == 'No':
        print("Debe registrarse primero\n")

    elif opciones_1 == 2:
      evento_2 = input("Inserte el nombre del evento\n")
      print(f"Su nuevo evento es {evento_2}")

    elif opciones_1 == 3:
        fecha_consulta = input("ingrese la fecha que desea consultar\n")
        for lista in listas_datos_finales:
            for fecha in lista_reservaciones:
                if fecha == fecha_procesada:
                    print("*"*80)
                    print("*"*20,f"Reporte de reservaciones para el dia {fecha}","*"*20)
                    print("*"*80)
                    print(lista_reservaciones)
                    print("*"*50)
                    print("{:<15} {:<15} {:<15} {:<15}".format("Sala","Cliente","Evento","Turno"))
                    print("*"*80)
                    print(f"{lista_reservaciones[5]}","   "*4,{lista_reservaciones[1]},"   "*4,{lista_reservaciones[2]},"   "*4,{lista_reservaciones[4]})
                    print("*"*35,"Fin del reporte","*"*35)
                    break
        
        print(lista_reservaciones)

    elif opciones_1 == 4:
      nuevo_cliente = input("Inserte su nombre:\n ")
      clave_unica = print(f"Su clave es {random.randrange(1000000)}\n")
  
    elif opciones_1 == 5:
        clave_sala = (random.randrange(10000))
        nombre_sala = input("Ingresa el nombre de la sala\n")
        print("Sala agregada:")
        print(sala)

    elif opciones_1 == 6:
      print("Gracias por su atencion")



